config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :users do
    member do
      get "show_favorites" => "users#show_favorites"
    end
  end
  resources :sessions
  resources :favorites
  resources :pictures do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :content, presence: true
  validates :content, length: { in: 1..140 }
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :favorites, dependent: :destroy

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  mount_uploader :image, ImageUploader
  validates :image, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, success: "#{favorite.picture.user.name}さんの投稿をお気に入りに登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, danger: "#{favorite.picture.user.name}さんの投稿をお気に入りから解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def show
    if logged_in?
      @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    end

  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, success: "編集しました！"
    else
      render :edit
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, success: "新規投稿しました！"
        PostMailer.post_mail(@picture).deliver  ##追記
      else
        render :new
      end
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, danger:"削除しました！"
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private

  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def ensure_correct_user
    @picture = Picture.find_by(id:params[:id])
    if @picture.user_id != current_user.id
      redirect_to pictures_path, danger:"権限がありません"
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), success: "ログインしました"
    else
      flash[:danger] = "ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to new_session_path , success: "ログアウトしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), success: "ユーザー情報を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, danger:"削除しました！"
  end

  def show_favorites
    @user = User.find(params[:id])
    @favorites = @user.favorites
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image, :image_cache, :password,
                                 :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    @user = User.find_by(id:params[:id])
    if @user.id != current_user.id
      redirect_to users_path, danger:"権限がありません"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IgClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Ig_Clone", root_path ,class: 'navbar-brand'%>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if logged_in? %>
              <li><%= link_to "Profile: #{current_user.name}", user_path(current_user.id) %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
              <li><%= link_to "favorites", show_favorites_user_path(current_user.id) %></li>
              <li><%= link_to "新規投稿", new_picture_path %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path %></li>
              <li><%= link_to "Login", new_session_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Pictures", pictures_path %></li>
            <li><%= link_to "Users", users_path %></li>
          </ul>
        </div>
      </div>
    </nav>

    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <%= msg.html_safe %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
      <div class="jumbotron">
        <fieldset>
          <% if @picture.new_record? %>
            <legend>新規投稿</legend>
          <% else %>
            <legend>編集</legend>
          <% end %>

          <%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
          <div class="form-group">
            <%= form.label :content ,class: "control-label" %>
            <%= form.text_field :content ,class: "form-control" ,placeholder:"content" %>
            <%= form.label :image ,class: "control-label" %>
            <% if @picture.new_record? %>
            <% else %>
              <%= image_tag @picture.image.url ,class: "img-responsive"%>
            <% end %>
            <%= form.file_field :image %>
            <%= form.hidden_field :image_cache %>
          </div>
          <% if @picture.new_record? %>
            <%= form.submit "新規投稿" ,class: "btn btn-info" %>
          <% else %>
            <%= form.submit "更新" ,class: "btn btn-danger" %>
          <% end %>
        <% end %>
      </fieldset>
    </div>
  </div>
</div>

app/views/pictures/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <fieldset>
        <legend>
          <h3>以下の内容で送信する</h3>
        </legend>

        <%= form_with(model: @picture, local: true) do |form| %>
        <div class="form-group">
          <%= form.hidden_field :content %>
          <p>content:<%= @picture.content %></p>
          <% if @picture.image && @picture.image.url %>
            <%= image_tag @picture.image.url ,class: "img-responsive"%>
          <% else %>
          <% end %>
          <%= form.hidden_field :image_cache %>
        </div>
        <%= form.submit "投稿",class: "btn btn-info" %>
        <%= form.submit "戻る",class: "btn btn-info" , name: 'back' %>
      <% end %>

      </fieldset>
    </div>
  </div>
</div>

app/views/pictures/edit.html.erb
<%= render 'form' %>

app/views/pictures/index.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="row">

      <% @pictures.each do |picture| %>
        <div class="col-sm-6 col-md-4">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= link_to image_tag(picture.image.url, size: '230x230'), picture_path(picture.id) %>

            </div>
            <div class="panel-footer">
              <%= link_to image_tag(picture.user.image.url, size: '50x50'), user_path(picture.user.id) %>
              <%= picture.content %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<%= render 'form' %>

app/views/pictures/show.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <legend>
        <h2 class="text-center">詳細</h2>
      </legend>
      <div class="mb-5 row">
        <div class="col-xl-4">
          <%= image_tag @picture.image.url, class: "img-responsive" %>
        </div>
        <div class="col-xl-8">
          <h3><%= @picture.content %></h3>
          <% if logged_in? && @picture.user_id == current_user.id  %>
            <%= link_to "編集", edit_picture_path(@picture.id), class: 'btn btn-info' %>
            <%= link_to '削除', picture_path(@picture.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger' %>
          <% else %>
          <% end %>

          <% if logged_in? %>
            <% unless @picture.user_id == current_user.id %>
              <% if @favorite.present? %>
                <%= link_to 'お気に入りを解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
              <% else %>
                <%= link_to 'お気に入りに入れる', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-info' %>
              <% end %>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "件のエラーがあります。") %>
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container ig_form">
  <fieldset>
    <% if @user.new_record? %>
      <legend>Sign Up</legend>
    <% else %>
      <legend>Edit</legend>
    <% end %>

    <%= form_with(model: @user, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name ,class: "control-label" %>
      <%= f.text_field :name ,class: "form-control" ,placeholder:"Name" %>

      <%= f.label :email ,class: "control-label"%>
      <%= f.email_field :email ,class: "form-control" ,placeholder:"Email" %>

      <%= f.label :image ,class: "control-label" %>
      <%= f.file_field :image %>

      <%= f.label :password ,class: "control-label" %>
      <%= f.password_field :password ,class: "form-control" %>

      <%= f.label :password_confirmation ,class: "control-label" %>
      <%= f.password_field :password_confirmation ,class: "form-control" %>
    </div>
    <% if @user.new_record? %>
      <%= f.submit "Create my account" ,class: "btn btn-info" %>
    <% else %>
      <%= f.submit "Update" ,class: "btn btn-info" %>
    <% end %>

    <% end %>
  </fieldset>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="row">
      <% @users.each do |user| %>

        <div class="col-sm-6 col-md-4">
          <div class="panel">
            <%= link_to image_tag(user.image.url, size: '230x230'), user_path(user.id) %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <legend>
        <h2 class="text-center">詳細</h2>
      </legend>

      <div class="mb-5 row">
        <div class="col-sm-4">
          <%= image_tag @user.image.url, class: "img-responsive" %>
        </div>
        <div class="col-sm-8">
          <h3><%= @user.name %></h3>
          <p><%= @user.email %></p>
          <%= link_to "お気に入り", show_favorites_user_path(@user.id), class: 'btn btn-success' %>
          <% if logged_in? && @user.id == current_user.id  %>
            <%= link_to "編集", edit_user_path(@user.id), class: 'btn btn-info' %>
            <%= link_to '削除', user_path(@user.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-primary' %>
          <% else %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show_favorites.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="row">
      <legend>
        <h2 class="text-center">お気に入り</h2>
      </legend>
      <div class="mb-5 row">
        <div class="col-sm-4">
          <%= image_tag @user.image.url, class: "img-responsive" %>
        </div>
        <div class="col-sm-8">
          <h3><%= @user.name %></h3>
          <p><%= @user.email %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="jumbotron">
    <div class="row">

      <% @favorites.each do |favorite| %>
        <div class="col-sm-6 col-md-4">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= image_tag favorite.picture.image.url , size: '230x230'%>
            </div>
            <div class="panel-footer">
              <%= image_tag favorite.picture.user.image.url , size: '50x50'%>
              <%= favorite.picture.user.name %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>